"""add purchase_date column to books_sales table

Revision ID: 0ea89661b261
Revises: 231ccd70b2b9
Create Date: 2024-09-22 17:27:21.379503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ea89661b261'
down_revision: Union[str, None] = '231ccd70b2b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books_sales', sa.Column('purchase_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books_sales', 'purchase_date')
    # ### end Alembic commands ###
