"""add quatity column to Book model

Revision ID: 67bbfe744718
Revises: 0ea89661b261
Create Date: 2024-09-22 17:32:09.429277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67bbfe744718'
down_revision: Union[str, None] = '0ea89661b261'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('quantity', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'quantity')
    # ### end Alembic commands ###
